config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index' 
  get '/' => 'home#newdata', :as => 'newdata_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fund_datum.rb
class FundDatum < ApplicationRecord
end

app/models/scheme_datum.rb
class SchemeDatum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
#Homepage Controller when i user reload the oage for the first time. In index used the if contion because 
#we can have the values from the form in url pamanetrs as we don't have to same them in database. 
#We are getting all the funds type from the databse to select form the user to get the NAV value of the prticular Fund
#used formatjs to append the calulated data
	def index
		@user_data_arr=[]#Array to show mupltple calculated records
		if params[:fund_type].nil?
			@fund=SchemeDatum.all#get all funds from one fundhouse
		else
			@currentdate='2019-11-06'
			#query to get the Past navvalue and the currentdate navvalue we can make this query using SP also and can execute SP here also.
			nav_query = "select net_assest_value,date from fund_data as fd, scheme_data as sd where (fd.date='#{params[:date]}' or fd.date='#{@currentdate}') and scheme_name = '#{params[:fund_type]}' and fd.scheme_code = sd.scheme_code"
			begin
				nav_data = ActiveRecord::Base.connection.execute(nav_query)#navvalue from query
			rescue ActiveRecord::RecordNotFound => error
				#can heandel error
				print error
			end

			begin
				nav_data.each do |data|
					if data["date"]==params[:date]
						@navvalue=data["net_assest_value"]#nav value of past date
						@units=(params[:amount].to_f/@navvalue.to_f).round(3)#units from totalamount/nav
					else
						#as i updated the data in Db on last 6-Nov-2019 so my current date is 6-Nov-2019
						@nav_value_current_date=data["net_assest_value"]#nav value of present date
					end
				end
				#check units are nil or not if units are nil then nav of past is not present in the DB
				if !@units.nil?
					@invested_anount=(@nav_value_current_date.to_f * @units).round(2)
					@user_data_arr.push("invested_anount"=>@invested_anount,"units"=>@units,"navvalue"=>@navvalue,"fundname"=>params[:fund_type],"amount"=>params[:amount],"date"=>params[:date])
				else
					@error="Selected Date Nav Value is not found for #{params[:fund_type]}"	
				end
				#Append the data in index.html file using _calculateddata.html file
				respond_to do |format|
					format.js
				end
			rescue ActiveRecord::RecordNotFound => error
				#can heandel error
				print error
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_calculateddata.html.erb
<% @user_data_arr.each do |data| %>
  <span>As per your invested Amount i.e <%= data["amount"] %> on the <%= data["fundname"] %> for the date <%= data["date"] %> the NAV value was <%= data["navvalue"] %>. So the Gained units are <%= data["units"] %>. Investment today would be worth Rs. <%= data["invested_anount"]%></span>
<%end%>

<span><%= @error%></span></br>

app/views/home/index.html.erb
<!-- TO Show on Header of page -->
<div id="show-list">

	<sapn>Calculate Investment</sapn>

	<!-- Form to calculate the Investment from the current Date -->
	<%= form_tag(newdata_page_path,  :method => "get",remote: true) do%>
	<!-- URL to get the data and then find the result according to that -->

		<!-- All Fund of one fund House from tabel Fund -->
		<%= select_tag "fund_type", options_for_select(@fund.collect{ |u| [u.scheme_name, u.scheme_name]}.insert(0, "Select Fund"),params[:fund_type]) %>

	  	<p>Amount:<%= text_field_tag "amount",(params[:amount]) %></p><!-- Amount By User -->

	  	<p>Date:<%= date_field_tag "date", (params[:date])%></p><!-- Date By User -->

	  	<%= button_tag  'Calculate Amount', :class => 'btn btn-primary' %>
	<% end  %>

	<div id="showdata"></div><!-- Show Calculated Data  -->	
</div>

app/views/home/index.js.erb
$('#show-list #showdata').append("<%= j render 'calculateddata' %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Srvfundtask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>